### ISSUE TITLE
Custom Event isn't be tracked by using applicationInsight

### ISSUE THREAD

**Issue by ricardoisdebugging** [rodolphocastro/rodolphocastro.github.io#32]
Hi, I am using azure application insight to track events of a self-built search engine written within vue. I first see your published article in "https://dev.to/ardc_overflow/monitorando-uma-aplicacao-vuejs-com-o-application-insights-9h1". I followed your solution and wrapped the application insight sdk as a service but export a function.

`import  { ApplicationInsights }  from '@microsoft/applicationinsights-web'

const appInsights = new ApplicationInsights({
  config: {
    instrumentationKey: "xx-xx-xx",
    autoTrackPageVisitTime: true,
    enableAutoRouteTracking: true,
    enableRequestHeaderTracking: true,
    enableResponseHeaderTracking: true
  }
})

appInsights.loadAppInsights();
appInsights.trackEvent();

export function useAppInsights () {
  return appInsights
}
`

Then in my search-view page (search.vue), I call the service of application insight and register two track events of a custom event and a pageview. 
`<script>
import { useAppInsights } from '../services/AppInsights'

useAppInsights().trackEvent("search page loaded!");
useAppInsights().trackPageView({name: 'search page'});

export default {};
</script>
`

The search.vue is integrated into the main.js using the router. 
router.js
`
import Search from './components/Search.vue'
import Product from './components/Product.vue'

const routers = [
  {
    path: '/search',
    name: 'Search',
    component: Search
  }, 
  {
    path: '/product',
    name: 'Product',
    component: Product
  },
]
export default routers
`
main.js->
`
import Vue from "vue";
import VueRouter from "vue-router";
import "element-ui/lib/theme-chalk/base.css";
import routers from "./router";
import ElementUI from "element-ui";
import "element-ui/lib/theme-chalk/index.css";
import App from "./App.vue";
import axios from "axios";

Vue.config.productionTip = false;

Vue.use(VueRouter);
Vue.use(ElementUI);
Vue.use(axios);

const router = new VueRouter({
  mode: "history",
  routes: routers,
});

new Vue({
  el: "#app",
  router,
  render: (h) => h(App),
});

`

But in my azure application-insight portal, I cannot see any events at all. 
![image](https://user-images.githubusercontent.com/33414765/111893706-7a0a4c00-8a3f-11eb-99d6-f2581b9b36cc.png)

May I ask if you have any solutions towards this condition?

**Comment by rodolphocastro** [comment]
Hey man, do you get any console errors when that happens? 

My main suspicion here would be that by the time that you `useAppInsights().trackEvent("search page loaded!")` on your component the instance still isn't ready to react to that 😅, thus that'd error out on your browser's console.

Another thing that could be at play here is if you're testing with any ad-blocker enabled. For instance, on my own blog, `uBlock Origin` renders AppInsights almost useless due to how it blocks telemetries and ads, the errors I see on my console are attached on the screenshot below 👇🏻 

![Firefox's console errors due to ad blocking](https://user-images.githubusercontent.com/2666310/111907045-60163c80-8a32-11eb-8094-0579ed349ce7.png)
